#! /usr/bin/env python

import rospy
from sensor_msgs.msg import LaserScan

def callback(msg):
	#obtain the minimun
    # values at 0 degree
    print msg.ranges[180]
    # values at 90 degree
    print msg.ranges[360]
    # values at 180 degree
    print msg.ranges[540]    
rospy.init_node('scan_values')
sub = rospy.Subscriber(rospy.get_param('scan_subscriber_topic_name'), LaserScan, callback)
rospy.spin()


